"""
InvestmentAdvisor - ADK Agent
Generated by: bedsheet deploy --target gcp
"""
from google.adk.agents import LlmAgent, ParallelAgent

# Tool definitions for InvestmentAdvisor (converted from Bedsheet @action decorators)

def delegate(**kwargs) -> str:
    return ''


# Tool definitions for collaborator agents
# Tools for MarketAnalyst

def get_stock_data(symbol: str) -> dict:
    """Fetch stock data (simulated for demo)."""
    stocks = {'NVDA': {'price': 875.5, 'change': '+3.2%', 'pe_ratio': 65.4, 'market_cap': '2.1T'}, 'AAPL': {'price': 178.25, 'change': '-0.5%', 'pe_ratio': 28.1, 'market_cap': '2.8T'}, 'MSFT': {'price': 378.9, 'change': '+1.1%', 'pe_ratio': 35.2, 'market_cap': '2.9T'}, 'GOOGL': {'price': 141.8, 'change': '+0.8%', 'pe_ratio': 24.5, 'market_cap': '1.8T'}, 'AMZN': {'price': 178.5, 'change': '+1.5%', 'pe_ratio': 62.3, 'market_cap': '1.9T'}}
    symbol_upper = symbol.upper()
    if symbol_upper in stocks:
        return {'symbol': symbol_upper, **stocks[symbol_upper]}
    return {'error': f'Unknown symbol: {symbol}', 'suggestion': 'Try NVDA, AAPL, MSFT, GOOGL, or AMZN'}


def get_technical_analysis(symbol: str) -> dict:
    """Get technical indicators (simulated)."""
    technicals = {'NVDA': {'rsi': 62.5, 'macd': 'bullish crossover', 'trend': 'uptrend', 'support': 820, 'resistance': 920}, 'AAPL': {'rsi': 45.2, 'macd': 'neutral', 'trend': 'sideways', 'support': 170, 'resistance': 185}, 'MSFT': {'rsi': 55.8, 'macd': 'bullish', 'trend': 'uptrend', 'support': 360, 'resistance': 400}, 'GOOGL': {'rsi': 52.3, 'macd': 'neutral', 'trend': 'sideways', 'support': 135, 'resistance': 155}, 'AMZN': {'rsi': 58.1, 'macd': 'bullish', 'trend': 'uptrend', 'support': 170, 'resistance': 190}}
    symbol_upper = symbol.upper()
    base = technicals.get(symbol_upper, {'rsi': 50, 'macd': 'neutral', 'trend': 'unknown'})
    return {'symbol': symbol_upper, **base}

# Tools for NewsResearcher

def search_news(query: str) -> dict:
    """Search recent news (simulated)."""
    news_db = {'nvidia': [{'headline': 'NVIDIA Reports Record Data Center Revenue', 'sentiment': 'positive'}, {'headline': 'AI Chip Demand Continues to Surge', 'sentiment': 'positive'}, {'headline': 'NVIDIA Announces New AI Supercomputer', 'sentiment': 'positive'}], 'apple': [{'headline': 'Apple Vision Pro Launches to Mixed Reviews', 'sentiment': 'neutral'}, {'headline': 'iPhone Sales Slow in China', 'sentiment': 'negative'}], 'microsoft': [{'headline': 'Microsoft Copilot Adoption Accelerates', 'sentiment': 'positive'}, {'headline': 'Azure Revenue Beats Expectations', 'sentiment': 'positive'}], 'google': [{'headline': "Google's Gemini AI Gains Enterprise Traction", 'sentiment': 'positive'}, {'headline': 'Alphabet Announces Cloud Revenue Growth', 'sentiment': 'positive'}, {'headline': 'DOJ Antitrust Trial Continues', 'sentiment': 'negative'}], 'amazon': [{'headline': 'AWS Revenue Growth Accelerates', 'sentiment': 'positive'}, {'headline': 'Amazon Prime Membership Hits New Highs', 'sentiment': 'positive'}]}
    query_lower = query.lower()
    for company, articles in news_db.items():
        if company in query_lower:
            return {'query': query, 'articles': articles, 'count': len(articles)}
    return {'query': query, 'articles': [], 'count': 0}


def analyze_sentiment(articles: list) -> dict:
    """Analyze sentiment from news articles."""
    if not articles:
        return {'sentiment': 'neutral', 'confidence': 0.0}
    sentiment_scores = {'positive': 1, 'neutral': 0, 'negative': -1}
    total = sum((sentiment_scores.get(a.get('sentiment', 'neutral'), 0) for a in articles))
    avg = total / len(articles) if articles else 0
    if avg > 0.3:
        sentiment = 'bullish'
    elif avg < -0.3:
        sentiment = 'bearish'
    else:
        sentiment = 'neutral'
    return {'sentiment': sentiment, 'confidence': round(min(abs(avg) + 0.5, 1.0), 2), 'articles_analyzed': len(articles)}

# Tools for RiskAnalyst

def analyze_volatility(symbol: str) -> dict:
    """Analyze volatility (simulated)."""
    volatility_data = {'NVDA': {'beta': 1.65, 'volatility_30d': '35.2%', 'max_drawdown_1y': '-25.4%', 'risk_rating': 'HIGH'}, 'AAPL': {'beta': 1.28, 'volatility_30d': '22.5%', 'max_drawdown_1y': '-15.2%', 'risk_rating': 'MODERATE'}, 'MSFT': {'beta': 0.92, 'volatility_30d': '19.2%', 'max_drawdown_1y': '-12.1%', 'risk_rating': 'LOW-MODERATE'}, 'GOOGL': {'beta': 1.05, 'volatility_30d': '25.8%', 'max_drawdown_1y': '-18.7%', 'risk_rating': 'MODERATE'}, 'AMZN': {'beta': 1.22, 'volatility_30d': '28.3%', 'max_drawdown_1y': '-20.5%', 'risk_rating': 'MODERATE-HIGH'}}
    symbol_upper = symbol.upper()
    base = volatility_data.get(symbol_upper, {'risk_rating': 'UNKNOWN'})
    return {'symbol': symbol_upper, **base}


def get_position_recommendation(symbol: str, risk_tolerance: str) -> dict:
    """Get position recommendation."""
    position_sizes = {'conservative': {'max_position': '2-3%', 'entry_strategy': 'Dollar-cost average over 3-6 months'}, 'moderate': {'max_position': '4-6%', 'entry_strategy': 'Split into 2-3 tranches'}, 'aggressive': {'max_position': '8-10%', 'entry_strategy': 'Can enter full position on dips'}}
    base = position_sizes.get(risk_tolerance.lower(), position_sizes['moderate'])
    return {'symbol': symbol.upper(), 'risk_tolerance': risk_tolerance, 'recommended_position': base['max_position'], 'entry_strategy': base['entry_strategy'], 'stop_loss': 'Consider 15-20% stop-loss for risk management', 'disclaimer': 'This is educational content, not personalized financial advice.'}


# Agent definition
# Collaborator agents
MarketAnalyst_agent = LlmAgent(
    name="MarketAnalyst",
    model="gemini-2.5-flash",
    instruction="""You are a market analyst specializing in stock analysis.
Use get_stock_data and get_technical_analysis to gather comprehensive data.
Provide clear, data-driven analysis with specific numbers and metrics.""",
    tools=[get_stock_data, get_technical_analysis,     ],
)

NewsResearcher_agent = LlmAgent(
    name="NewsResearcher",
    model="gemini-2.5-flash",
    instruction="""You are a news researcher focused on financial news.
Use search_news to find recent articles, then analyze_sentiment for overall mood.
Report key headlines and the overall sentiment (bullish/bearish/neutral).""",
    tools=[search_news, analyze_sentiment,     ],
)

RiskAnalyst_agent = LlmAgent(
    name="RiskAnalyst",
    model="gemini-2.5-flash",
    instruction="""You are a risk analysis specialist.
Use analyze_volatility to assess stock risk metrics.
Use get_position_recommendation to suggest position sizing.
Always emphasize the importance of risk management.""",
    tools=[analyze_volatility, get_position_recommendation,     ],
)


# Orchestrator (parallel)
root_agent = ParallelAgent(
    name="InvestmentAdvisor",
    sub_agents=[MarketAnalyst_agent, NewsResearcher_agent, RiskAnalyst_agent],
)
